# Stage 1: Build the React app
FROM node:18-alpine AS build

# ENV http_proxy="http://proxy.scrubbingcenter.com:3128/"
# ENV https_proxy="http://proxy.scrubbingcenter.com:3128/"


WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# RUN mkdir -p /app/dist/assets && cp -r /app/src/assets/* /app/dist/assets/

# Stage 2: Serve with a lightweight static server
FROM nginx:alpine

# Remove default nginx site
RUN rm -rf /usr/share/nginx/html/*

# Copy build output
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx configurations
COPY nginx.http.conf /etc/nginx/conf.d/default.conf
COPY nginx.https.conf /etc/nginx/conf.d/default.https.conf

# Copy entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80 443
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
