FROM python-base

# ENV HTTP_PROXY="http://proxy.scrubbingcenter.com:3128/"
# ENV HTTPS_PROXY="http://proxy.scrubbingcenter.com:3128/"
# ENV http_proxy="http://proxy.scrubbingcenter.com:3128/"
# ENV https_proxy="http://proxy.scrubbingcenter.com:3128/"

# Set working directory
WORKDIR /app

# Copy application code
COPY ./netknight /app/netknight
COPY ./pyproject.toml /app/pyproject.toml
COPY ./entrypoint.sh /entrypoint.sh
RUN mkdir /app/testing_fiiles/

# Install Python dependencies

RUN pip install ./

# Make entrypoint executable
RUN chmod +x /entrypoint.sh

# Expose API port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "netknight:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
